language: php
branches:
  only:
  - dev
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=2df54d9b00fef949f3c58d93b9eccbad08a741db47706ebdfbcdfc92cfb33afb
install: composer install --no-interaction --prefer-dist
script: phpunit
before_install:
- openssl aes-256-cbc -K $encrypted_72a15151d2bc_key -iv $encrypted_72a15151d2bc_iv
  -in travisci.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: 34.92.170.56
matrix:
  include:
  - php: 7.3
    after_success:
      - ssh root@34.92.170.56 ./travis-shell-script-dev.sh
  - node_js: 10
    language: node_js
    install: yarn
    script: echo '测试'
